export const ROUTES = {
  HOME: '/',
  ARTICLES: '/between-the-pages',
  ARTICLE: '/between-the-pages/:slug',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  APP: '/app',
  SCAN: '/app/scan',
  SCAN_DETAIL: '/app/scan/:id',
  COLLECTION: '/app/collection/:id',
  BOOK: '/app/book/:id',
  SETTINGS: '/app/settings',
  SHARED: '/shared/:token',
};
